#!/usr/bin/env bash
# Run a small UCBlock subset with BranchAndXSolver driven by
# LagrangianDualRelaxationSolver.

source "$(dirname "$0")/../../batch_common.sh"

DEFAULT_EXE=./UCBlock_test
DEFAULT_PAR=BSPar-BX.txt
parse_batch_args "$@"

DATADIR=../../UCBlock/data/nc4/UC_Data/T-Ramp

for size in 10 20 50; do
  for seed in 1 2; do
    run_test "$exe" "${DATADIR}/${size}_0_${seed}_w.nc4" \
      -S "$par" -B InnerBCfg.txt
  done
done