#!/usr/bin/env bash
#
# usage: batch < bpar file > < bspar file >

source "$(dirname "$0")/../batch_common.sh"

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

#set=resilient-data/tmp_smspp_*.nc
set=plan4res-data/FirstSetofInstances/*.nc4

for what in ../../UCBlock/data/nc4/$set; do

    run_test ./compare_formulations "$what" MetaConfig1.txt MetaConfig2.txt BSCfg1.txt BSCfg2.txt

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
