#!/usr/bin/env bash

source "$(dirname "$0")/../batch_common.sh"

DATADIR=../MMCFBlock/data

LDS_MMCF_test=${1:-./LDS_MMCF_test}

for what in ${DATADIR}/Canad/*.dat; do

  run_test "$LDS_MMCF_test" "$what" s

done
