#!/usr/bin/env bash

source "$(dirname "$0")/../batch_common.sh"

DATADIR=../MMCFBlock/data

LDS_MMCF_test=${1:-./LDS_MMCF_test}

# Mnetgen - - - - - - - - - - - - - - - - - - - -

for i in 64; do
  for j in 4 8 16 32 64; do
    for (( h = 1 ; h < 13 ; h++ )); do

      what=${DATADIR}/Mnetgen/$i-$j-$h

      run_test "$LDS_MMCF_test" "$what" m

    done
  done
done

for i in 128; do
  for j in 4 8 16 32 64 128; do
    for (( h = 1 ; h < 13 ; h++ )); do

      what=${DATADIR}/Mnetgen/$i-$j-$h

      run_test "$LDS_MMCF_test" "$what" m

    done
  done
done

#for i in 256; do
#  for j in 4 8 16 32 64 128 256; do
#    for (( h = 1 ; h < 13 ; h++ )); do
#
#      what=${DATADIR}/Mnetgen/$i-$j-$h
#
#      printf "[$what m]: "
#
#      "$LDS_MMCF_test" $what m
#
#      retVal=$?
#      if [ $retVal -ne 0 ]; then
#        exit 1
#      fi
#
#    done
#  done
#done
