#!/usr/bin/env bash

source "$(dirname "$0")/../batch_common.sh"

DATADIR=../../MCFBlock/data

wchg=255
#rounds=40

MCF_MILP_test=${1:-./MCF_MILP_test}

for type in net goto; do

  for (( seed = 0; seed < 3 ; seed++ )); do

    #for sz in 8_8 8_32 10_8 10_64 12_8 14_8
    for sz in 8_8 8_32 10_8 10_64 12_8; do
      for h in 1 2 3 4 5; do

        what=${DATADIR}/nc4/${type}${sz}_${h}.nc4

        run_test "$MCF_MILP_test" "$what" "$seed" "$wchg" "$rounds"

      done # h
    done   # sz

  done # seed
done   # type
