#!/usr/bin/env bash
#
# usage: batchQL_I < exe file >
#        < exe file > = path of the executable file, default ./MILPSolver_QuadFunction_test
#
# runs MILPSolver_QuadFunction_test over the QL_I instance set (objective/constraints combination
# encoded in this script's DATADIR and TYPE)

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../../../batch_common.sh"

DATADIR=./ObjQ_ConsL
TYPE=I

MILPSolver_QuadFunction_test=${1:-./MILPSolver_QuadFunction_test}

for what in "$DATADIR"/*; do

  run_test "$MILPSolver_QuadFunction_test" "$what" "$TYPE"

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
