#!/usr/bin/env bash
#
# usage: batchLC_C < exe file >
#        < exe file > = path of the executable file, default ./MILPSolver_QuadFunction_test
#
# runs MILPSolver_QuadFunction_test over the LC_C instance set (objective/constraints combination
# encoded in this script's DATADIR and TYPE)

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../../../batch_common.sh"

DATADIR=./ObjL_ConsC
TYPE=C

MILPSolver_QuadFunction_test=${1:-./MILPSolver_QuadFunction_test}

for what in "$DATADIR"/*; do

  run_test "$MILPSolver_QuadFunction_test" "$what" "$TYPE"

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
