#!/usr/bin/env bash

source "$(dirname "$0")/../batch_common.sh"

seed=264
wchg=127
n_repeat=50

BinaryKnapsackBlock_test=${1:-./BinaryKnapsackBlock_test}

for N in 100 500 3000; do

  for delta in 0.005 0.05 0.6; do

    for nW in 0 0.2 0.7 1; do

      for nP in 0 0.2 0.7 1; do

        for nI in 0 0.2 0.8 1; do

          for nM in 0 0.2 0.7 1; do

            run_test "$BinaryKnapsackBlock_test" "$seed" "$wchg" "$N" "$n_repeat" "$delta" "$nW" "$nP" "$nI" "$nM"

          done
        done
      done
    done
  done
done
