#!/usr/bin/env bash
#
# usage: batch_acad < par file >  < solver > < log file >
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < solver > = 0 or 1, default 0
#        < log file > = name of log file, default no log
#
# runs all pure thermal and hydrothermal academic instances
#
# for LagranngianDualSolver + BundleSolver:
# correct value of tStar: 1e+0

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

exe=./LDS_UC_test

if [ $# -gt 0 ]; then
   par=$1
else
   par=BSPar-2S.txt
fi
if [ $# -gt 1 ]; then
   slv=$2
else
   slv=0
fi
if [ $# -gt 2 ]; then
   mlf=$4
fi

#  pure thermal academic instances- - - - - - - - - - - - - - - - - - - - - -

DATADIR=../../UCBlock/data/nc4/UC_Data/T-Ramp

for size in 10 20 50 75 100 200; do
  for (( seed = 1 ; seed < 6 ; seed++ )); do

    what=${DATADIR}/${size}_0_${seed}_w.nc4

    if [ -z "$mlf" ]; then
       printf "[$what $par $slv]: "
       "$exe" $what $par $slv
    else
       printf "[$what $par $slv]: " >> $mlf
       "$exe" $what $par $slv >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done

# hydrothermal academic instances - - - - - - - - - - - - - - - - - - - - - -

DATADIR=../../UCBlock/data/nc4/UC_Data/HT-Ramp

for size in 20_10 50_20 75_35 100_50 150_75 200_100; do
  for (( seed = 1 ; seed < 3 ; seed++ )); do

    what=${DATADIR}/${size}_${seed}_w.nc4

    if [ -z "$mlf" ]; then
       printf "[$what $par $slv]: "
       "$exe" $what $par $slv
    else
       printf "[$what $par $slv]: " >> $mlf
       "$exe" $what $par $slv >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

  done
done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
