#!/usr/bin/env bash
#
# usage: batch-resilient < par file > < log file >
#        < par file > = BlockSolverConfig file, default BSPar.txt
#        < log file > = name of log file, default no log
#
# runs all the energy community instances and checks that the PyPsa objective
# value matches the given reference one

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

exe=./LDS_UC_test

if [ $# -gt 1 ]; then
   par=$2
else
   par=BSPar.txt
fi
if [ $# -gt 2 ]; then
   mlf=$3
fi

# reference objective values dictionary - - - - - - - - - - - - - - - - - - -
# each entry: [ filename ] = PyPsa objective value
# filenames must match exactly the .nc files in the current directory

declare -A REF_OBJ

REF_OBJ[tmp_smspp_1n_1c_1g.nc]=4.221761376e+09
REF_OBJ[tmp_smspp_1n_1c_1g_1h.nc]=4.984288994e+08
REF_OBJ[tmp_smspp_1n_1c_1gext.nc]=4.055269613e+09
REF_OBJ[tmp_smspp_2n_1c_1g_1b.nc]=3.944062665e+09
REF_OBJ[tmp_smspp_2n_1c_1gext_1bext_2l.nc]=3.887187461e+09
REF_OBJ[tmp_smspp_2n_1c_1gext_1bext_2lext.nc]=7.034743762e+08
REF_OBJ[tmp_smspp_2n_2c_1g_1lext.nc]=6.720604306e+09
REF_OBJ[tmp_smspp_3n_3c_1gext_1h_1bext_2l.nc]=2.907246492e+09
REF_OBJ[tmp_smspp_3n_3c_2gext_1l_1ml.nc]=1.302415551e+10
REF_OBJ[tmp_smspp_3n_3c_2gext_1lext_1mlext.nc]=2.898358885e+06
REF_OBJ[tmp_smspp_sector_1n_1cn_1gn.nc]=-6.883586038e+04
REF_OBJ[tmp_smspp_sector_1n_1cn_1gnext.nc]=2.399258678e+05

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

for what in ../../UCBlock/data/nc4/resilient-data/tmp_smspp_*.nc; do

    # skip if pattern did not match any file
    if [ ! -f "$what" ]; then
      continue
    fi

    base=$(basename "$what")
    ref=${REF_OBJ[$base]}

    if [ -z "$ref" ]; then
      echo "No reference objective defined for file: $base"
      exit 1
    fi

    if [ -z "$mlf" ]; then
       printf "[$what $par 0 $ref]: "
      "$exe" $what $par 0 $ref
    else
       printf "[$what $par 0 $ref]: " >> $mlf
      "$exe" $what $par 0 $ref >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
