#!/usr/bin/env bash
#
# usage: batch_ec < exe file > < par file > < log file >
#        < exe file > = path of the executable file, default LDS_UC_test
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < log file > = name of log file, default no log
#
# runs all the pure energy community instances

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

LDS_UC_test=${1:-./LDS_UC_test}

if [ $# -gt 1 ]; then
   par=$2
else
   par=BSPar-2S.txt
fi
if [ $# -gt 2 ]; then
   mlf=$3
fi

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

for what in ../../UCBlock/data/nc4/EC_Data/EC_CO_*.nc4 \
            ../../UCBlock/data/nc4/EC_Data/EC_NC_*.nc4; do

    if [ -z "$par" ]; then
      if [ -z "$mlf" ]; then
        printf "[$what]: "
      else
        printf "[$what]: " >> $mlf
      fi
    else
      if [ -z "$mlf" ]; then
        printf "[$what $par]: "
      else
        printf "[$what $par]: " >> $mlf
      fi
    fi

    if [ -z "$mlf" ]; then
      "$LDS_UC_test" $what $par
    else
      "$LDS_UC_test" $what $par >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
