#!/usr/bin/env bash
#
# usage: batch-acad < exe file > < par file > < solver > < log file >
#        < exe file > = path of the executable file, default LDS_UC_test
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < solver > = 0 or 1, default 0
#        < log file > = name of log file, default no log
#
# runs all pure thermal and hydrothermal academic instances
#
# for LagrangianDualSolver + BundleSolver:
# correct value of tStar: 1e+0

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../../batch_common.sh"

DEFAULT_EXE=./LDS_UC_test
DEFAULT_PAR=BSPar-2S.txt
DEFAULT_SLV=0
parse_batch_args "$@"

#  pure thermal academic instances- - - - - - - - - - - - - - - - - - - - - -

DATADIR=../../UCBlock/data/nc4/UC_Data/T-Ramp

for size in 10 20 50 75 100 200; do
  for (( seed = 1 ; seed < 6 ; seed++ )); do

    what=${DATADIR}/${size}_0_${seed}_w.nc4

    run_test "$exe" "$what" -S "$par" -B InnerBCfg.txt -w "$slv"

  done
done

# hydrothermal academic instances - - - - - - - - - - - - - - - - - - - - - -

DATADIR=../../UCBlock/data/nc4/UC_Data/HT-Ramp

for size in 20_10 50_20 75_35 100_50 150_75 200_100; do
  for (( seed = 1 ; seed < 3 ; seed++ )); do

    what=${DATADIR}/${size}_${seed}_w.nc4

    run_test "$exe" "$what" -S "$par" -B InnerBCfg.txt -w "$slv"

  done
done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
