#!/usr/bin/env bash
#
# usage: batch_p4r < par file > < solver > < log file >
#        < par file > = BlockSolverConfig file, default BSPar-2S.txt
#        < solver > = 0 or 1, default 0
#        < log file > = name of log file, default no log
#
# runs all the plan4res public instances
#
# for LagrangianDualSolver + BundleSolver:
# correct value of tStar: 1e-2
# correct value of dblCtOff: 0.1

# command line parameter setup- - - - - - - - - - - - - - - - - - - - - - - -

exe=./LDS_UC_test

if [ $# -gt 0 ]; then
   par=$1
else
   par=BSPar-2S.txt
fi
if [ $# -gt 1 ]; then
   slv=$2
else
   slv=0
fi
if [ $# -gt 2 ]; then
   mlf=$3
fi

# run all the instances - - - - - - - - - - - - - - - - - - - - - - - - - - -

for what in ../../UCBlock/data/nc4/plan4res-data/FirstSetofInstances/*.nc4; do

    if [ -z "$mlf" ]; then
       printf "[$what $par $slv]: "
       "$exe" $what $par $slv
    else
       printf "[$what $par $slv]: " >> $mlf
       "$exe" $what $par $slv >> $mlf
    fi

    retVal=$?
    if [ $retVal -ne 0 ]; then
      exit 1
    fi

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
