#!/usr/bin/env bash

source "$(dirname "$0")/../../batch_common.sh"

DATADIR=../../UCBlock/data/nc4/1UC_Data

wchg=133
#iter=0

TUDPS_test=${1:-./TUDPS_test}

# ACAD + Lagrangian - - - - - - - - - - - - - - - - - - - -

for wf in 0 1 2 3 4 5 6; do
  i=24
  #for i in 24 96; do
    # skip DP, pt, SU, SD and SUSD formulations for 96 problems
    #if [ $wf -ge 2 ] && [ $i -eq 96 ]; then
      #continue
    #fi
    j=1
    #for j in 1 12 16 23; do
      for (( h = 1 ; h <= 100 ; h++ )); do
        for (( seed = 0 ; seed < 20 ; seed++ )); do
          #seed=0

          what=${DATADIR}/${i}/S${j}ramp${h}_${i}.nc4

          run_test "$TUDPS_test" "$what" "$seed" "$wchg" "$wf" "$iter"

        done
      done
    #done
  #done
done
