#!/usr/bin/env bash
#
# usage: batch < exe file >
#        < exe file > = path of the executable file, default ./MMCFBlock_test
#
# runs the Canad and Mnetgen MMCF instances through LagrangianDualSolver

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../batch_common.sh"

DATADIR=data

MMCFBlock_test=${1:-./MMCFBlock_test}

# Canad - - - - - - - - - - - - - - - - - - - -

for what in ${DATADIR}/Canad/*.dat; do

  run_test "$MMCFBlock_test" "$what" -B BPar.txt -S BSPar.txt -t s

done

# Mnetgen - - - - - - - - - - - - - - - - - - - -

for i in 64; do
  for j in 4 8 16 32 64; do
    for (( h = 1 ; h < 13 ; h++ )); do

      what=${DATADIR}/Mnetgen/$i-$j-$h

      run_test "$MMCFBlock_test" "$what" -B BPar.txt -S BSPar.txt -t m

    done
  done
done

for i in 128; do
  for j in 4 8 16 32 64 128; do
    for (( h = 1 ; h < 13 ; h++ )); do

      what=${DATADIR}/Mnetgen/$i-$j-$h

      run_test "$MMCFBlock_test" "$what" -B BPar.txt -S BSPar.txt -t m

    done
  done
done

#for i in 256; do
#  for j in 4 8 16 32 64 128 256; do
#    for (( h = 1 ; h < 13 ; h++ )); do
#
#      what=${DATADIR}/Mnetgen/$i-$j-$h
#
#      printf "[$what m]: "
#
#      "$MMCFBlock_test" $what m
#
#      retVal=$?
#      if [ $retVal -ne 0 ]; then
#        exit 1
#      fi
#
#    done
#  done
#done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
