#!/usr/bin/env bash
#
# usage: batch-c < exe file >
#        < exe file > = path of the executable file, default ./MMCFBlock_test
#
# runs the Canad MMCF instances through LagrangianDualSolver, twice: the
# subproblems, i.e., the MCFBlock of the commodities, solved by a :MILPSolver
# (BSPar.txt) and by the network simplex of LEMON (BSPar-lemon.txt)

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../../batch_common.sh"

DATADIR=data

MMCFBlock_test=${1:-./MMCFBlock_test}

for what in ${DATADIR}/Canad/*.dat; do

  run_test "$MMCFBlock_test" "$what" -B BPar.txt -S BSPar.txt -t s
  run_test "$MMCFBlock_test" "$what" -B BPar.txt -S BSPar-lemon.txt -t s

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
