#!/usr/bin/env bash
#
# usage: batch-aggr < exe file > < aggregations > < seeds > < log file >
#        < exe file >      = path of the executable file, default
#                            ./MMCFBlock_test
#        < aggregations >  = values of dblCmpAggr to try, default
#                            "0 0.02 0.1 0.5 1"
#        < seeds >         = values of intCmpAggrSeed to try, default 42
#        < log file >      = name of the log file, default no log (stdout)
#
# Runs some Canad MMCF instances in the *knapsack* formulation, i.e. the one
# of batch-k, over a grid of values of the *partial aggregation* of the
# components: dblCmpAggr = 0 leaves each of them a component of the master
# problem, 1 makes them a single one, and x in between gives round( 1 / x )
# groups. The knapsack formulation has one BinaryKnapsackBlock per arc, i.e.
# many small subproblems that are solved by dynamic programming, and a master
# problem that grows with their number: this is the arrangement in which the
# aggregation is supposed to pay, and the one Frangioni asked to measure.
#
# The parameter is set in the ComputeConfig of the inner BundleSolver, i.e. in
# LDCfg.txt, which is therefore rewritten for each value and put back as it
# was at the end.

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../../batch_common.sh"

DATADIR=data

MMCFBlock_test=${1:-./MMCFBlock_test}
aggrs=${2:-"0 0.02 0.1 0.5 1"}
seeds=${3:-"42"}
mlf=${4:-}

CFG=LDCfg.txt

# put the configuration back as it was, whatever happens - - - - - - - - - -

cp "${CFG}" "${CFG}.orig"
trap 'mv -f "${CFG}.orig" "${CFG}"' EXIT

for aggr in ${aggrs}; do
  for cmpseed in ${seeds}; do

    cp -f "${CFG}.orig" "${CFG}"
    cfg_set_par "${CFG}" dblCmpAggr "${aggr}"
    cfg_set_par "${CFG}" intCmpAggrSeed "${cmpseed}"

    for what in p33 p34 p35 p36 p41 p42 p43 p44; do

      run_timed "[aggr ${aggr} seed ${cmpseed} ${what}]" \
                "$MMCFBlock_test" "${DATADIR}/Canad/${what}.dat" \
                -B BPar-K.txt -S BSPar-K.txt -t s

    done
  done
done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
