#!/usr/bin/env bash

source "$(dirname "$0")/../batch_common.sh"

what=511
#what=0
#iter=3

LagBFunction_test=${1:-./LagBFunction_test}

for nf in -2 -11; do

  if [ $nf -eq -2 ]; then
    t=1
  else
    t=3
  fi

  # z = 1 is LagBFunction treated as non-easy, -1 is treated as easy
  for z in 1 -1; do
    let nt=t*z

    #for size in 2 10 50 100
    for size in 2 10 50; do
      for dens in 3 1.1; do
        for (( seed = 0 ; seed < 20 ; seed++ )); do

          run_test "$LagBFunction_test" "$seed" "$what" "$size" "$nf" "$nt" "$dens" "$iter"

        done
      done
    done
  done
done
