#!/usr/bin/env bash

source "$(dirname "$0")/../batch_common.sh"

what=3
#iter=0

BoxSolver_test=${1:-./BoxSolver_test}

for size in 2 10 50 100 1000; do
  for (( seed = 0 ; seed < 20 ; seed++ )); do

    run_test "$BoxSolver_test" "$seed" "$what" "$size" "$iter"

  done
done
