#!/usr/bin/env bash

source "$(dirname "$0")/../../batch_common.sh"

DATADIR=./ObjQ_ConsL
TYPE=I

quad_test=${1:-./quad_test}

for what in "$DATADIR"/*; do

  run_test "$quad_test" "$what" "$TYPE"

done
