#!/usr/bin/env bash
#
# usage: batchLC_I < exe file >
#        < exe file > = path of the executable file, default ./quad_test
#
# runs quad_test over the LC_I instance set (objective/constraints combination
# encoded in this script's DATADIR and TYPE)

# shared CLI/run helpers - - - - - - - - - - - - - - - - - - - - - - - - - -
source "$(dirname "$0")/../../batch_common.sh"

DATADIR=./ObjL_ConsC
TYPE=I

quad_test=${1:-./quad_test}

for what in "$DATADIR"/*; do

  run_test "$quad_test" "$what" "$TYPE"

done

# the end - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
